name: single_touch_gesture
description: A Flutter package that prevents multiple gesture recognition, allowing only one touch at a time.
version: 1.0.0
homepage: https://github.com/YashrajsinhYz/single_touch_gesture
repository: https://github.com/YashrajsinhYz/single_touch_gesture
issue_tracker: https://github.com/YashrajsinhYz/single_touch_gesture/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <5.0.0"

topics:
  - single
  - touch
  - gestures
  - multiple
  - prevention
